Repository SauravMukherjee44/CodeIN-Community-Website, pull requests merged in 2022-03, with the labels that each got.

#119 fixed the oppurtunities card to be of equal size on mobile screens
  index.html
Labels: GSSoC22, Level 1

#128 Added animations to landing page for mobile screen
  index.html
Labels: GSSoC22, Level 1

#131 docs: Add PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSoC22, Level 1

#133 added header and footer in benefits page
  benefit.html
Labels: GSSoC22, Level 2

#136 Different hover colors added to social media icons
  assets/css/main.css
  index.html
Labels: GSSoC22

#135 improved responsiveness addressing issue #132
  assets/css/main.css
  assets/css/responsive.css
  index.html
Labels: GSSoC22, Level 1

#105 added blog page
  assets/css/blog.css
  assets/img/blog/low-tech-high.jpg
  blog.html
  index.html
Labels: GSSoC22, Level 3

#154 border fix for opportunity section
  assets/css/bootstrap.min.css
Labels: GSSoC22, Level 1

#156 enhaneced benefits of joining section
  assets/css/main.css
  index.html
Labels: GSSoC22, Level 1

#158 Blog_titlecase_edit
  blog.html
  index.html
Labels: GSSoC22

#162 Added Hovering effect
  assets/css/bootstrap-grid.css
  assets/css/bootstrap-grid.css.map
  assets/css/bootstrap-grid.min.css
  assets/css/bootstrap-grid.min.css.map
  assets/css/bootstrap-reboot.css
  assets/css/bootstrap-reboot.css.map
  assets/css/bootstrap-reboot.min.css
  assets/css/bootstrap-reboot.min.css.map
  assets/css/bootstrap.css
  assets/css/bootstrap.css.map
  assets/css/bootstrap.min.css.map
  assets/vanilla-tilt/.gitattributes
  assets/vanilla-tilt/.idea/misc.xml
  assets/vanilla-tilt/.idea/modules.xml
  assets/vanilla-tilt/.idea/runConfigurations.xml
  assets/vanilla-tilt/.idea/vanilla-tilt.js.iml
  assets/vanilla-tilt/.idea/vcs.xml
  assets/vanilla-tilt/CONTRIBUTORS.md
  assets/vanilla-tilt/LICENSE
  assets/vanilla-tilt/README.md
  assets/vanilla-tilt/build.js
  assets/vanilla-tilt/dist/vanilla-tilt.babel.js
  assets/vanilla-tilt/dist/vanilla-tilt.babel.min.js
  assets/vanilla-tilt/dist/vanilla-tilt.js
  assets/vanilla-tilt/dist/vanilla-tilt.min.js
  assets/vanilla-tilt/lib/README.md
  assets/vanilla-tilt/lib/vanilla-tilt.es2015.js
  assets/vanilla-tilt/lib/vanilla-tilt.js
  assets/vanilla-tilt/package.json
  assets/vanilla-tilt/src/vanilla-tilt.js
  assets/vanilla-tilt/test/index.html
  assets/vanilla-tilt/vanilla-tilt.d.ts
  index.html
Labels: GSSoC22, Level 1

#164 docs: Added Issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/doc_issue.yaml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: GSSoC22, Level 1

#167 made the blog section responsive
  assets/css/blog.css
  blog.html
Labels: GSSoC22, Level 1

#168 added email validation in form
  benefit.html
  blog.html
  index.html
Labels: GSSoC22, Level 1

#176 Improved go to top button
  assets/css/main.css
Labels: good first issue, GSSoC22

#175 Text overflow issue solved
  assets/css/blog.css
Labels: GSSoC22, Level 1

#171 improved formatting for mentor details
  benefit.html
Labels: GSSoC22, Level 1

#180 Changed styling of social icons
  assets/css/main.css
Labels: GSSoC22, Level 1

#187 Added policy page
  Privacy Policy Page/policy.css
  Privacy Policy Page/policy.html
Labels: GSSoC22, Level1

#201 improved validation errors on contact form
  CSS/styles.css
  assets/css/main.css
Labels: GSSoC22, Level1

#203 blogs added in home section.. view more button added in oppurtunities…
  assets/css/blog.css
  assets/css/main.css
  assets/css/oppurtunity.css
  assets/js/blog.js
  blog.html
  index.html
  opportunity.html
Labels: GSSoC22, Level2

#208 Added Hover Effect
  assets/css/main.css
Labels: GSSoC22, Level1

#214 fixes the team section cards for #213
  assets/css/swipper.css
  assets/js/swipper.js
  assets/scss/main.css
  assets/scss/main.css.map
  assets/scss/responsive.css
  assets/scss/responsive.css.map
  index.html
Labels: GSSoC22, Level1

#216 Seo optimization
  .DS_Store
  assets/.DS_Store
  assets/img/.DS_Store
  assets/vanilla-tilt/.DS_Store
  benefit.html
  blog.html
  index.html
  opportunity.html
Labels: GSSoC22, Level2
