Repository SauravMukherjee44/CodeIN-Community-Website, pull requests merged in 2022-10, with the labels that each got.

#320 [fixes] External links should open on a new tab
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#310 Changes in Hacktober.html to add Responsiveness
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#305 Update scss/main.css
  assets/scss/main.css
Labels: Hacktoberfest-accepted

#327 Discord Logo will not dissaper
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#332 Fixed Blogs section
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#328 Added more opportunities in opportunity.html
  assets/img/opportunity/Hacktoberfest.jpg
  assets/img/opportunity/fossasia.jpeg
  assets/img/opportunity/goldmensachs.jpg
  assets/img/opportunity/gsoc.png
  assets/img/opportunity/mlh.png
  opportunity.html
Labels: Hacktoberfest-accepted, hacktoberfest

#338 Closes #333 : The mentor discord link on benefits page was fixed
  benefit.html
Labels: Hacktoberfest-accepted, hacktoberfest

#342 Nav links in hacktoberfest page fixed
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#349 Added all the social media handle links in the Benefits page
  assets/css/main.css
  benefit.html
Labels: Hacktoberfest-accepted, hacktoberfest

#353 Resized the blog cards equally
  assets/css/blog.css
  assets/css/main.css
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#351 Navigation link fixed
  assets/css/main.css
  assets/scss/main.css
  benefit.html
Labels: Hacktoberfest-accepted, hacktoberfest

#335 Join Our Team's Section Links will open in new tab.
  hacktoberfest2022.html
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#355 Search fix
  blog.html
Labels: Hacktoberfest-accepted, hacktoberfest

#365 Added a testimonial
  assets/img/team/ayush_raj.png
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#368 Navbar HacktoberFest2022 li
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#361 Subscriber box Modified!!
  JS/Counter1.js
Labels: Hacktoberfest-accepted, hacktoberfest

#391 Added new Testimonial.
  assets/img/team/AHARNA-HAQUE.webp
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#385 add darkmode fiture
  .vscode/settings.json
  assets/css/darkmode.css
  assets/js/darkmode.js
  assets/scss/main.css
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#384 Sponsor nav link fixed in hacktoberfest page
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#389 Updated code for new tab opening
  benefit.html
  blog.html
  giveaway.html
  hacktoberfest2022.html
  index.html
  opportunity.html
Labels: Hacktoberfest-accepted, hacktoberfest

#392 Updated text-align : center for mobile view on nav-links
  CSS/styles.css
Labels: Hacktoberfest-accepted, hacktoberfest

#382 issue#356 -- made sponsor section responsive on all pages
  benefit.html
  blog.html
  giveaway.html
  hacktoberfest2022.html
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#373 Added more blogs
  CSS/styles.css
  assets/css/responsive.css
  assets/img/blog/austrology.jpg
  assets/img/blog/being-by-doing.jpg
  assets/img/blog/google-open-sourse.png
  blog.html
Labels: Hacktoberfest-accepted, hacktoberfest

#371 Add Drop Shadow & hover in Sponsor Logos
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#370 Hacktoberfest cards changes
  assets/css/blog.css
  assets/css/hacktoberfest.css
  assets/css/oppurtunity.css
  blog.html
  hacktoberfest2022.html
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#399 Added two new opportunities
  assets/img/opportunity/gcp.png
  assets/img/opportunity/gtechcamp.png
  opportunity.html
Labels: Hacktoberfest-accepted, hacktoberfest

#396 Updated Testimonial of mine
  assets/img/team/ayushjain.jpg
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#401 Added new Testimonial.#357
  assets/img/team/dimple.jpg
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#398 Fix the join us button width in mobile view
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#362 create a class
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#431 Enhanced buttons in navbar
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#430 corrected blog page css and deleted unnecessary code
  blog.html
Labels: Hacktoberfest-accepted, hacktoberfest

#426 Removed my name from team members
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#416 hrithik raj added testimonial
  assets/img/team/hrithik_raj.jpeg
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#433 Social share button
  hacktoberfest2022.html
Labels: good first issue, hacktoberfest

#424 Fixed issue #369
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#417 Set a minimum height of home page
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#445 Invisible Text in FAQ section on DarkTheme Plugin #442
  assets/css/darkmode.css
  assets/css/main.css
  assets/js/darkmode.js
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#444 Website turned into Yellow Theme
  assets/CodeIN-yellow.png
  assets/css/blog.css
  assets/css/contactSection.css
  assets/css/hacktoberfest.css
  assets/css/main.css
  assets/css/oppurtunity.css
  assets/css/swipper.css
  assets/img/Call_center-cuate.png
  assets/img/Marketing-pana.png
  assets/img/about/Social biography-amico.png
  assets/img/hero-area.png
  assets/img/hero-area.png.svg
  assets/img/one-yellow.png
  hacktoberfest2022.html
  index.html
Labels: enhancement, Hacktoberfest-accepted, hacktoberfest

#440 corrected spacing between Opportunity and Blogs in navbar
  assets/css/oppurtunity.css
  opportunity.html
Labels: Hacktoberfest-accepted, hacktoberfest

#448 FAQ section and Benefit.html turned yellow
  assets/css/main.css
  assets/img/about/Social biography-amico.png
  benefit.html
Labels: Hacktoberfest-accepted, hacktoberfest

#438 added contributors section to the website using the github api
  CSS/index.css
  JS/index.js
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#454 added linebreak in social share button of hacktoberfest2022 page for better look
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#471 Submit button's color changed
  assets/css/contactSection.css
Labels: Hacktoberfest-accepted, hacktoberfest

#475 Added SCROLL TO TOP BUTTON
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#465 css error:FAQ.css fixed wrong mime type
  CSS/index.css
  JS/index.js
  blog.html
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#453 adding sitemp.xml file for better crawling by google
  sitemap.xml
Labels: Hacktoberfest-accepted, hacktoberfest

#460 submit button and error message text changed to black
  assets/js/contact-form-script.min.js
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#461 Updated Meta Tags For Search Engine Optimization
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#504 Added section to feature Youtube Videos.
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#517 Fixed Testimonials
  assets/css/main.css
  assets/css/swipper.css
Labels: Hacktoberfest-accepted, hacktoberfest

#516 Added a Preloader
  assets/img/preloader.gif
  preloader/index.html
  preloader/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#511 fixing the join us button issue
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#510 Fixed issue #486
  assets/css/blog.css
  assets/css/darkmode.css
  assets/css/oppurtunity.css
  assets/js/darkmode.js
Labels: Hacktoberfest-accepted, hacktoberfest

#505 Aligned cards image of opportunity section
  assets/img/opportunity/100daysofcode.png
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#500 removed unnecessary spacing after Join Us Section on Hacktoberfest Page
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest

#492 Update oppurtunity.css
  assets/css/oppurtunity.css
Labels: Hacktoberfest-accepted, hacktoberfest

#550 Footer links getting smaller on hover and fix proper spacing in the form of footer
  assets/css/oppurtunity.css
  index.html
Labels: bug, 🚦 status : Requested changes

#542 Fixed Go to Project button to redirect user on a new tab
  hacktoberfest2022.html
Labels: Hacktoberfest-accepted, hacktoberfest, ☑ status : Approved by 1 maintainer

#541 fixed join us button scrolling
  index.html
Labels: bug, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#540 Added Margin
  CSS/index.css
Labels: bug, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#557 reformatted the fonts on benefits.html to make it look more appealing
  CSS/styles.css
  assets/css/main.css
  benefit.html
Labels: Hacktoberfest-accepted, hacktoberfest

#526 Responsive footer and navbar
  blog.html
  index.html
Labels: 🚦 status : Requested changes

#524 updated index.css
  CSS/index.css
Labels: Hacktoberfest-accepted, hacktoberfest

#560 Color of Active Links in Navbar changes to yellow as we scroll to provide a clear reference to users.
  assets/css/main.css
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#561 refomatted the colors of the icons in Join us section
  CSS/styles.css
  index.html
Labels: enhancement, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#570 Fixed sponsor navigation issue
  blog.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#571 the color of icon change when we hover on them in Join Us cards
  CSS/styles.css
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#575 Newsletter subscription popup added
  JS/Counter1.js
  index.html
Labels: enhancement, Hacktoberfest-accepted, hacktoberfest

#577 header & footer onclick issue solved
  hacktoberfest2022.html
Labels: 🚦 status : Requested changes

#593 Top performers of 100days of code
  100daysofcodeWinners.html
  assets/css/100daysofcode.css
  assets/css/main.css
  assets/img/100daysofcode.png
  assets/img/Recruitment-Journey.png
  assets/img/certificate.png
  assets/img/goodies.png
  index.html
Labels: enhancement, Hacktoberfest-accepted, hacktoberfest

#597 added the colors to the socials icons present in the footer
  index.html
Labels: bug, ☑ status : Approved by 1 maintainer

#590 Resolved the CLICK HERE issue
  index.html
Labels: bug, hacktoberfest, ☑ status : Approved by 1 maintainer

#582 Fixed input-box alignment in footer section.
  assets/css/main.css
  index.html
Labels: bug, good first issue, ☑ status : Approved by 1 maintainer

#578 Search Bars of Blog.html and hacktoberfest.html are now completely responsive
  blog.html
  hacktoberfest2022.html
Labels: bug, good first issue, hacktoberfest, ☑ status : Approved by 1 maintainer

#508 styles changes
  CSS/index.css
  JS/index.js
  index.html
Labels: bug, good first issue, hacktoberfest, ☑ status : Approved by 1 maintainer

#615 Add files via upload
  hacktoberfest2022.html
  responsive.css
Labels: bug, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#619 Fixes for proper working of dark mode toggle
  assets/css/main.css
  assets/js/darkmode.js
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#618 Updated Counter1.js for issue #606
  JS/Counter1.js
Labels: Hacktoberfest-accepted, hacktoberfest

#614 documentation Closes #101
  index.html
Labels: documentation, Hacktoberfest-accepted, 🚦 status : Requested changes

#603 Fixed link opening on new tab
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#610 issue 579 solved except for contact form
  JS/index.js
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest, 🚦 status : Requested changes

#627 FAQ's section background and text color changed
  assets/css/darkmode.css
  assets/js/darkmode.js
  index.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#631 Added new Testimonial
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#635 customized the Join Us button by adding appropriate hover effect
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#628 Resolved issue #608
  assets/js/contact-form-script.min.js
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#668 Fixed background and text color in darkmode
  assets/css/darkmode.css
  assets/css/main.css
  assets/css/swipper.css
  assets/js/darkmode.js
  index.html
Labels: bug, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#654 Successfully updated the Google forms links to open on separate Tabs
  index.html
  opportunity.html
Labels: enhancement, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#623 fixed home button glitch on hacktoberfest22.html
  hacktoberfest2022.html
Labels: bug, ☑ status : Approved by 1 maintainer

#621 grammatical errors in readme fixed
  README.md
Labels: documentation, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#544 Add meta tags for OpenGraph and Twitter
  index.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#679 Changed the UI of 404 page(seems attractive)
  404.css
  404.html
Labels: Hacktoberfest-accepted, hacktoberfest

#677 Added Hover effect on links in 'FAQs' section of CodeIN Community website
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#670 Update hacktoberfest2022.html [Made embedded video frame responsive]
  hacktoberfest2022.html
Labels: bug, Hacktoberfest-accepted, 🚦 status : Requested changes

#642 Corrected Style in [More Options]
  CSS/index.css
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#703 Corrected Grammatical error in Hero-Section of index.html
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#701 changed the color of scroll to top
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#697 Fixed some issues in Contact section
  assets/css/contactSection.css
  assets/css/darkmode.css
  assets/css/main.css
  assets/js/darkmode.js
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#696 Scroll to Top button colour fixed
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#690 Closes #600 - Blog Buttons not in the center
  blog.html
Labels: Hacktoberfest-accepted, hacktoberfest

#688 Fixed Overlapping projects
  assets/css/hacktoberfest.css
Labels: Hacktoberfest-accepted, hacktoberfest

#689 Closes #681 resolved - Event Card Animation
  CSS/index.css
  assets/css/main.css
  index.html
Labels: Hacktoberfest-accepted, hacktoberfest

#683 Adding Search icon
  assets/css/hacktoberfest.css
  hacktoberfest2022.html
Labels: enhancement, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#725 Changed Giveaway Icons, It was choppy cut-outs before in giveaway.html
  assets/img/TshirtWinIcon.png
  assets/img/VoucherWinIcon.png
  giveaway.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#685 Updated blog.html to close issue #605
  blog.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#719 corrected the colors of socials in the footer of benefits page
  benefit.html
Labels: Hacktoberfest-accepted, hacktoberfest

#739 Title: Change testimonial text color
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#733 changes for header in /main.css
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest

#740 Fixed a Typo
  hacktoberfest2022.html
Labels: bug, good first issue, Hacktoberfest-accepted, ☑ status : Approved by 1 maintainer

#746 Added a new blog to blog.html
  blog.html
Labels: enhancement, good first issue, Hacktoberfest-accepted, 🚦 status : Requested changes

#756 Added a new blog about web development
  blog.html
Labels: Hacktoberfest-accepted, hacktoberfest

#751 Styled 'More options' in navbar
  assets/css/main.css
Labels: Hacktoberfest-accepted, hacktoberfest
